### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by applecat** [Lepozepo/cloudinary#1]
See this in console in 5 seconds after image upload:

```
[Error] RangeError: Maximum call stack size exceeded.
    forEach (underscore.js, line 157)
    clone (ejson.js, line 424)
    (анонимная функция) (id-map.js, line 108)
    forEach (id-map.js, line 84)
    clone (id-map.js, line 107)
    clone (ejson.js, line 416)
    (анонимная функция) (ejson.js, line 425)
    forEach (underscore.js, line 164)
    clone (ejson.js, line 424)
    (анонимная функция) (ejson.js, line 425)
    forEach (underscore.js, line 164)
    clone (ejson.js, line 424)
    (анонимная функция) (ejson.js, line 425)
    forEach (underscore.js, line 164)
    clone (ejson.js, line 424)
```

My template:

```
  {{#cloudinary_upload callback="save_url"}}
    <input type="file">
  {{/cloudinary_upload}}
```

Config:

```
if (Meteor.isServer) {
  //SERVER
  Cloudinary.config({
      cloud_name: '...',
      api_key: '...',
      api_secret: '...'
  });

  Meteor.methods({
    save_url:function(response){
        console.log('Add '+response.upload_data+' to the id of '+response.context);
    }
  });
}

if (Meteor.isClient) {
  //CLIENT
  $.cloudinary.config({
      cloud_name:'...'
  });
}
```

**Comment by oriharel** [comment]
I have the same issue, only with 1 particular image, which is size 3.9MB. I'm using the free account for now. Is this a limitation?

```
RangeError: Maximum call stack size exceeded
    at String.match (native)
    at RegExp.<anonymous> (/Users/oriharel/reversim/reversim-summit-2016/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/_fix-re-wks.js:25:39)
    at String.match (/Users/oriharel/reversim/reversim-summit-2016/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.regexp.match.js:8:34)
    at /Users/oriharel/reversim/reversim-summit-2016/node_modules/cloudinary/lib/uploader.js:67:34
    at call_api (/Users/oriharel/reversim/reversim-summit-2016/node_modules/cloudinary/lib/uploader.js:398:22)
    at Object.exports.upload (/Users/oriharel/reversim/reversim-summit-2016/node_modules/cloudinary/lib/uploader.js:64:12)
    at uploadProfilePicture (users.js:92:23)
```
